import { mobileApiGet } from "./mobileApi";

export type PracticeSetSummary = {
  id: number;
  title: string;
  subject: string;
  formLevel: string;
  questionCount: number;
  difficultyLevel: string;
};

export type MathLineDiagram = {
  type: "line-chart";
  questionIndex?: number;
  title?: string;
  subtitle?: string;
  equationLabel?: string;
  xAxisLabel?: string;
  yAxisLabel?: string;
  points: Array<{ x: number; y: number; label?: string }>;
};

export type BiologyCellFocusLabel =
  | "cellWall"
  | "cellMembrane"
  | "vacuole"
  | "chloroplast"
  | "nucleus"
  | "cytoplasm";

export type StructuredQuestionDiagram = {
  type: "biology-cell";
  questionIndex?: number;
  title?: string;
  subtitle?: string;
  layout: "plant" | "animal" | "comparison";
  state?: "normal" | "hypotonic" | "hypertonic";
  focusLabels?: BiologyCellFocusLabel[];
};

export type PracticeSetQuestion = {
  id: number;
  sortOrder: number;
  questionText: string;
  questionType: string;
  difficulty: string;
  options: string[];
  correctAnswer: string;
  explanation: string | null;
  /** Optional: include full question text (e.g., with A-D options) for /api/rag/grade. */
  questionForGrade?: string;
  /** Optional diagram generated by /api/rag/generate for Math questions. */
  diagram?: MathLineDiagram;
  /** Optional app-rendered structured diagram spec. */
  structuredDiagram?: StructuredQuestionDiagram;
  /** Qwen image model URL for Biology/Chemistry/Physics educational diagrams. */
  diagramImageUrl?: string;
  /** Total marks for subjective items (from generated Markah: line). */
  maxMarks?: number;
};

function optionsArrayFromParsed(parsed: unknown): string[] | null {
  if (!Array.isArray(parsed)) return null;
  return parsed.map((x) => String(x).trim()).filter((s) => s.length > 0);
}

/** DB/text often stores JSON arrays with escaped quotes: `[\"3\", \"4\", \"5\", \"6\"]` or double-encoded strings. */
function parseOptionsFromString(input: string, depth = 0): string[] | null {
  if (depth > 6) return null;
  const t = input.trim();
  if (!t) return [];

  const candidates: string[] = [];
  const push = (s: string) => {
    if (!candidates.includes(s)) candidates.push(s);
  };
  push(t);
  push(t.replace(/\\"/g, '"'));
  if (t.startsWith('"') && t.endsWith('"')) {
    push(t.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, "\\"));
  }

  for (const candidate of candidates) {
    try {
      const parsed = JSON.parse(candidate) as unknown;
      const arr = optionsArrayFromParsed(parsed);
      if (arr !== null) return arr;
      if (typeof parsed === "string") {
        const nested = parseOptionsFromString(parsed, depth + 1);
        if (nested !== null && nested.length > 0) return nested;
      }
    } catch {
      /* try next */
    }
  }

  const braced = (x: string) => x.trim().startsWith("[") && x.trim().endsWith("]");
  if (braced(t)) {
    for (const rawInner of [t, t.replace(/\\"/g, '"')]) {
      const inner = rawInner.trim().slice(1, -1);
      const parts: string[] = [];
      const re = /"((?:[^"\\]|\\.)*)"/g;
      let m: RegExpExecArray | null;
      for (m = re.exec(inner); m !== null; m = re.exec(inner)) {
        parts.push(m[1].replace(/\\"/g, '"').replace(/\\\\/g, "\\"));
      }
      if (parts.length > 0) {
        return parts.map((p) => p.trim()).filter(Boolean);
      }
    }
  }

  return null;
}

function normalizeQuestionOptions(raw: unknown): string[] {
  if (Array.isArray(raw)) {
    return raw.map((x) => String(x).trim()).filter((s) => s.length > 0);
  }
  if (typeof raw === "string") {
    return parseOptionsFromString(raw) ?? [];
  }
  return [];
}

function coercePracticeQuestion(row: unknown): PracticeSetQuestion {
  const r = row as Record<string, unknown>;
  const optSource =
    r.options ??
    r.questionOptions ??
    r["question_options"] ??
    r["questionOptions"];

  const options = normalizeQuestionOptions(optSource);

  return {
    id: Number(r.id ?? r.question_id ?? 0),
    sortOrder: Number(r.sortOrder ?? r.sort_order ?? 0),
    questionText: String(r.questionText ?? r.question_text ?? ""),
    questionType: String(r.questionType ?? r.question_type ?? ""),
    difficulty: String(r.difficulty ?? ""),
    options,
    correctAnswer: String(r.correctAnswer ?? r.correct_answer ?? ""),
    explanation:
      r.explanation === undefined || r.explanation === null
        ? null
        : String(r.explanation),
  };
}

type ListResponse = {
  data?: {
    sets: Array<
      Omit<PracticeSetSummary, "difficultyLevel"> & {
        difficultyLevel?: string | null;
      }
    >;
  };
  error?: string;
};

type DetailResponse = {
  data?: {
    set: {
      id: number;
      title: string;
      subject: string;
      formLevel: string;
      questionCount: number;
    };
    questions: PracticeSetQuestion[];
  };
  error?: string;
};

export async function fetchPracticeSetList(): Promise<PracticeSetSummary[]> {
  const res = await mobileApiGet<ListResponse>("/practice-sets");
  const sets = res.data?.sets;
  if (!sets) {
    throw new Error("Invalid practice sets response");
  }
  return sets.map((set) => ({
    ...set,
    difficultyLevel: (set.difficultyLevel ?? "mixed").toString(),
  }));
}

export async function fetchPracticeSetDetail(setId: number): Promise<{
  set: {
    id: number;
    title: string;
    subject: string;
    formLevel: string;
    questionCount: number;
  };
  questions: PracticeSetQuestion[];
}> {
  const res = await mobileApiGet<DetailResponse>(`/practice-sets/${setId}`);
  const data = res.data;
  if (!data?.set || !Array.isArray(data.questions)) {
    throw new Error("Invalid practice set detail response");
  }
  const questions: PracticeSetQuestion[] = data.questions.map((row) => coercePracticeQuestion(row));
  return { set: data.set, questions };
}
