import type { QuestionAnalysis } from "../../types";

export type AssessmentIntentFamily =
  | "recall"
  | "explanation"
  | "description"
  | "comparison"
  | "effects_evaluative"
  | "process"
  | "humanities"
  | "definition"
  | "calculation"
  | "general";

export type AssessmentIntentCategory =
  | "state"
  | "name"
  | "list"
  | "identify"
  | "explain"
  | "why"
  | "describe"
  | "compare"
  | "differentiate"
  | "advantages"
  | "disadvantages"
  | "effects"
  | "process"
  | "justify"
  | "evaluate"
  | "predict"
  | "define"
  | "calculate"
  | "general";

export type EvidenceUnitType = "fact" | "stage" | "claim" | "entity" | "dimension" | "justification";

export type EvidenceUnit = {
  id: string;
  type: EvidenceUnitType;
  content: string;
  /**
   * Minimal creditable essence of this marking point — the shortest phrase a
   * student must express to earn the mark (e.g. "cannot be derived", "kilogram").
   * Generated by the same rubric LLM call as `content`, uniformly for every
   * subject/question. Scoring measures student overlap against THIS (short)
   * phrase, not the long `content`, so a correct-but-brief answer is not
   * structurally penalised. Optional for backward-compat: when absent it is
   * derived deterministically at runtime from `aliases`/`content`.
   */
  coreConcept?: string;
  aliases: string[];
  creditWeight: number;
  /**
   * Extraction / evaluator hint: this unit is essential for a complete answer.
   * NOT used for chain-walk gating — use relations + `supports` topology instead.
   * @see requiredForCorrectness (alias during migration)
   */
  required: boolean;
  /** Optional alias for `required` — essential for correctness, not chain order. */
  requiredForCorrectness?: boolean;
  /** Parent unit ids that must be demonstrated before this unit can progress on a chain. */
  supports?: string[];
};

export type EvidenceRelationType =
  | "causes"
  | "enables"
  | "contrasts"
  | "sequence_next"
  | "justifies"
  | "predicts_from";

export type EvidenceRelation = {
  id: string;
  type: EvidenceRelationType;
  from: string;
  to: string;
  requiredForMarks: boolean;
};

export type MarkRuleKind =
  | "count_distinct_units"
  | "coverage_chain"
  | "ordered_stages"
  | "paired_entities"
  | "claim_plus_reason";

export type MarkRule = {
  kind: MarkRuleKind;
  maxMarks: number;
  /**
   * When true (count_distinct_units only): any N distinct valid units earn up to maxMarks —
   * used for list/recall/open-topic questions, NOT calculations or explanation chains.
   * Scorer: min(maxMarks, count of demonstrated credit units); ignores unit order.
   */
  openPool?: boolean;
  /** Set during generation for calculation questions. */
  calcPolicy?: "answer_only" | "show_working";
  /** Subject-specific calculation rule set (chemistry, physics, or generic). */
  calcDomain?: "chemistry" | "physics" | "general";
};

export type AssessmentIntent = {
  category: AssessmentIntentCategory;
  family: AssessmentIntentFamily;
  assessedUnderstanding: string;
  isCompound: boolean;
  analysis: QuestionAnalysis;
};

/**
 * One dimension of a comparison question: a single concept/axis on which the
 * compared entities are contrasted, together with the requirement each entity
 * must satisfy and the marks the dimension carries.
 *
 * Produced by the rubric builder so the grading engine can evaluate each entity
 * and dimension independently, instead of inferring contrast from contrast-word
 * regexes over rubric text.
 */
export type ComparisonDimension = {
  /** The concept being compared (e.g. "charge carriers", "melting point"). */
  dimension: string;
  /** What the first entity must express to satisfy this dimension. */
  entityARequirement: string;
  /** What the second entity must express to satisfy this dimension. */
  entityBRequirement: string;
  /** Marks carried by this comparison dimension. */
  marks: number;
};

/**
 * First-class comparison structure for comparison-family questions.
 *
 * Additive and optional: the atomic `EvidenceUnit[]` remain the scoring
 * substrate (one credit unit per contrasted side), so grading and partial
 * credit are unchanged when this is absent. When present it makes the compared
 * entities and dimensions explicit for evaluation, transparency, and audit.
 */
export type ComparisonModel = {
  /** The entities the question asks the student to compare. */
  entities: string[];
  dimensions: ComparisonDimension[];
};

/**
 * Examiner-style question decomposition (produced BEFORE units / model answer).
 * The question alone drives requirements and mark allocation; textbook must not invent marks.
 */
export type ExaminerRequirement = {
  id: string;
  /** Stem fragment / clause this requirement comes from. */
  stemFragment: string;
  commandWord: string;
  /** What the student must answer for this requirement. */
  whatIsAsked: string;
};

export type ExaminerMarkingPointPlan = {
  id: string;
  requirementId: string;
  /**
   * Structural demand kind: fact_recall | reason_mechanism | contrast |
   * importance_application | definition | calculation_stage | general
   */
  demandKind: string;
  /** One assessable requirement — NOT a full model-answer sentence. */
  assessableRequirement: string;
  /** Short phrase a student must express to earn this mark. */
  coreConcept: string;
  /** Whole marks for this point (usually 1; no half-marks). */
  marks: number;
};

export type ExaminerQuestionDecomposition = {
  requirements: ExaminerRequirement[];
  markingPoints: ExaminerMarkingPointPlan[];
  recommendedMaxScore: number;
  /** Short examiner rationale for the split (audit / prompts). */
  examinerRationale: string;
};

export type AssessmentCaseFile = {
  v: 3;
  question: string;
  subject: string;
  form: string;
  maxScore: number;
  intent: AssessmentIntent;
  assessedUnderstanding: string;
  units: EvidenceUnit[];
  relations: EvidenceRelation[];
  markRule: MarkRule;
  referenceModelAnswer?: string;
  /**
   * Structured comparison model for comparison-family questions.
   * Optional/additive — atomic `units` remain the scoring substrate; this makes
   * the compared entities and dimensions explicit for the grading engine.
   */
  comparison?: ComparisonModel;
  /**
   * Examiner question decomposition that produced the marking points.
   * Question → decomposition → mark allocation → units → model answer → grading.
   */
  decomposition?: ExaminerQuestionDecomposition;
  chunkRefs: string[];
  contextSource: "textbook" | "llm_fallback" | "embedded_mark_scheme";
  /** ISO timestamp when calculation reference answer passed independent verification. */
  verifiedAt?: string;
  /** How the cached calculation answer was verified before storage. */
  verificationMethod?: "reverse_check" | "dual_computation" | "pending_review";
  /** Set when verification failed — answer not cached; needs human review. */
  verificationNote?: string;
};

/** Pre-verified calculation answer from the chunk pipeline — skips redundant solve/verify in ACF build. */
export type VerifiedCalculationAnswer = {
  referenceModelAnswer: string;
  verifiedAt: string;
  verificationMethod: "reverse_check" | "dual_computation";
};

export type DemonstratedUnit = {
  unitId: string;
  quote: string;
  valid: boolean;
  /**
   * True when this award was confirmed by the semantic meaning verifier
   * (the LLM concept check) rather than by deterministic token overlap.
   *
   * The downstream deterministic gates still apply grounding, de-duplication,
   * and score caps to these awards, but they MUST NOT revoke a
   * semantically-verified award merely because it has low lexical overlap with
   * the marking point — accepting valid paraphrases is precisely the intent.
   */
  semanticallyVerified?: boolean;
};

export type DemonstratedRelation = {
  relationId: string;
  quote: string;
};

export type MissingGap = {
  id: string;
  kind: "unit" | "relation";
  label: string;
  reason: string;
};

export type UnderstandingDemonstration = {
  unitsDemonstrated: DemonstratedUnit[];
  relationsDemonstrated: DemonstratedRelation[];
  unitsMissing: MissingGap[];
  relationsMissing: MissingGap[];
  invalidClaims: { text: string; reason: string }[];
};

export type { ChainWalkResult } from "../scoring/coverageChainScorer";
export type { GradingContext } from "../case/gradingContext";

export type AssessmentCaseSourceMeta = {
  v: 3;
  pipeline: "evidence_centric";
  contextSource: "textbook" | "llm_fallback" | "embedded_mark_scheme";
  chunkRefs: string[];
  referenceModelAnswer?: string;
  intentFamily?: AssessmentIntentFamily;
  intentCategory?: AssessmentIntentCategory;
  verifiedAt?: string;
  verificationMethod?: "reverse_check" | "dual_computation" | "pending_review";
};

export type StoredAssessmentCase = {
  caseId: string;
  questionHash: string;
  subject: string;
  form: string;
  questionText: string;
  maxScore: number;
  acf: AssessmentCaseFile;
  sourceRef?: string;
};

/** DB wrapper stored in rag_rubrics.ideas column */
export type AssessmentCaseDbPayload = {
  v: 3;
  acf: AssessmentCaseFile;
};
